package structs

// Order 订单结构体
// 对应数据库中的ims_order表
type Order struct {
	ID                   int     `json:"id" gorm:"column:id;primaryKey;autoIncrement"`
	Weid                 int     `json:"weid" gorm:"column:weid"`
	Ocid                 int     `json:"ocid" gorm:"column:ocid"`
	CatID                int     `json:"cat_id" gorm:"column:cat_id"`
	HcatID               int     `json:"hcat_id" gorm:"column:hcat_id"`
	Sid                  int     `json:"sid" gorm:"column:sid"`
	Cardorderid          int     `json:"cardorderid" gorm:"column:cardorderid"`
	IsCashregister       int     `json:"is_cashregister" gorm:"column:is_cashregister"`
	Hid                  int     `json:"hid" gorm:"column:hid"`
	Ptype                int     `json:"ptype" gorm:"column:ptype"`
	Otype                int     `json:"otype" gorm:"column:otype"`
	Deliverymode         int     `json:"deliverymode" gorm:"column:deliverymode"`
	CateIds              string  `json:"cate_ids" gorm:"column:cate_ids"`
	Sendto               int     `json:"sendto" gorm:"column:sendto"`
	TuanFoundID          int     `json:"tuan_found_id" gorm:"column:tuan_found_id"`
	TuanID               int     `json:"tuan_id" gorm:"column:tuan_id"`
	MsID                 int     `json:"ms_id" gorm:"column:ms_id"`
	Timesmum             int     `json:"timesmum" gorm:"column:timesmum"`
	IsTimes              int     `json:"is_times" gorm:"column:is_times"`
	IsTiming             int     `json:"is_timing" gorm:"column:is_timing"`
	Distance             float64 `json:"distance" gorm:"column:distance"`
	IsErrands            int     `json:"is_errands" gorm:"column:is_errands"`
	OrderNumAlias        string  `json:"order_num_alias" gorm:"column:order_num_alias"`
	PaySubject           string  `json:"pay_subject" gorm:"column:pay_subject"`
	UID                  int     `json:"uid" gorm:"column:uid"`
	Aid                  string  `json:"aid" gorm:"column:aid"`
	ReturnPoints         int     `json:"return_points" gorm:"column:return_points"`
	PayPoints            int     `json:"pay_points" gorm:"column:pay_points"`
	PointsPrice          float64 `json:"points_price" gorm:"column:points_price"`
	PointsOrder          int     `json:"points_order" gorm:"column:points_order"`
	Name                 string  `json:"name" gorm:"column:name"`
	Email                string  `json:"email" gorm:"column:email"`
	Tel                  string  `json:"tel" gorm:"column:tel"`
	TakeAddressID        int     `json:"take_address_id" gorm:"column:take_address_id"`
	ShippingName         string  `json:"shipping_name" gorm:"column:shipping_name"`
	AddressID            int     `json:"address_id" gorm:"column:address_id"`
	ShippingTel          string  `json:"shipping_tel" gorm:"column:shipping_tel"`
	ShippingProvinceName string  `json:"shipping_province_name" gorm:"column:shipping_province_name"`
	ShippingCityName     string  `json:"shipping_city_name" gorm:"column:shipping_city_name"`
	ShippingDistrictName string  `json:"shipping_district_name" gorm:"column:shipping_district_name"`
	ShippingAddress      string  `json:"shipping_address" gorm:"column:shipping_address"`
	ShippingMethod       string  `json:"shipping_method" gorm:"column:shipping_method"`
	Latitude             string  `json:"latitude" gorm:"column:latitude"`
	Longitude            string  `json:"longitude" gorm:"column:longitude"`
	PaymentCode          string  `json:"payment_code" gorm:"column:payment_code"`
	AuthCode             string  `json:"auth_code" gorm:"column:auth_code"`
	PayFrom              string  `json:"pay_from" gorm:"column:pay_from"`
	PayResult            string  `json:"pay_result" gorm:"column:pay_result"`
	OfflinePayTime       int     `json:"offline_pay_time" gorm:"column:offline_pay_time"`
	IsOfflinePay         int     `json:"is_offline_pay" gorm:"column:is_offline_pay"`
	PayMethodID          int     `json:"pay_method_id" gorm:"column:pay_method_id"`
	GoodsgiftcardID      int     `json:"goodsgiftcard_id" gorm:"column:goodsgiftcard_id"`
	Remark               string  `json:"remark" gorm:"column:remark"`
	Hangingpoint         string  `json:"hangingpoint" gorm:"column:hangingpoint"`
	Total                float64 `json:"total" gorm:"column:total"`
	IsAdditional         int     `json:"is_additional" gorm:"column:is_additional"`
	Additional           float64 `json:"additional" gorm:"column:additional"`
	OrderStatusID        int     `json:"order_status_id" gorm:"column:order_status_id"`
	IsComment            int     `json:"is_comment" gorm:"column:is_comment"`
	IsExpress            int     `json:"is_express" gorm:"column:is_express"`
	IP                   string  `json:"ip" gorm:"column:ip"`
	UserAgent            string  `json:"user_agent" gorm:"column:user_agent"`
	CreateTime           int     `json:"create_time" gorm:"column:create_time"`
	BeginTime            int     `json:"begin_time" gorm:"column:begin_time"`
	EndTime              int     `json:"end_time" gorm:"column:end_time"`
	UpdateTime           int     `json:"update_time" gorm:"column:update_time"`
	Customtext           string  `json:"customtext" gorm:"column:customtext"`
	PayTime              int     `json:"pay_time" gorm:"column:pay_time"`
	StartTime            int     `json:"start_time" gorm:"column:start_time"`
	CompleteTime         int     `json:"complete_time" gorm:"column:complete_time"`
	AdditionalPayTime    int     `json:"additional_pay_time" gorm:"column:additional_pay_time"`
	HasInvoice           int     `json:"has_invoice" gorm:"column:has_invoice"`
}
